### ISSUE TITLE
New try with WMTS in EPSG:3006 

### ISSUE THREAD

**Issue by pedwik** [BruTile/BruTile#44] opened 2016-06-08 16:16 UTC
I am having a new go at trying to get a WMTS service work which is "native" EPSG:3006, with the latest code. I added this code at line 34 to Brutile.Demo in MainWindow.xaml.cs:

`
Layers.Children.Add(ToRadioButton("LM topowebb", LantMaterietTopowebbTileSourceTest.Create)); 
`

And this class to project Brutile.Samples.Common:

`
using BruTile.Wmts;
namespace BruTile.Samples.Common
{
    public static class LantMaterietTopowebbTileSourceTest
    {
        public static ITileSource Create()
        {
            Uri uri = new Uri("https://api.lantmateriet.se/open/topowebb-ccby/v1/wmts/token/7cdfdab81eba86d0bc4fbb328165e9a/?request=GetCapabilities&version=1.1.1&service=wmts");
            var req = WebRequest.Create(uri);
            var resp = req.GetResponseAsync();
            ITileSource tileSource;
            using (var stream = resp.Result.GetResponseStream())
            {
                var tileSources = WmtsParser.Parse(stream);
                tileSource = tileSources.First(s => s.Name.ToLower() == "topowebb");
            }
            return tileSource;
        }
    }
}`

There are no errors now, but no map data is displayed when runing Brutile.Demo and selecting node "LM topowebb", just a red dot. The tile source object has expected values as far as I can see. Any ideas?

**Comment by pauldendulk** [comment] 2016-06-09 07:00
Had a look. I don't see anything strange in your code. This layer is working properly in, for example, qgis?

**Comment by pedwik** [comment] 2016-06-09 08:20
Yes, in QGIS it works.

**Comment by pauldendulk** [comment] 2016-06-09 08:39
I will take a closer look.

**Comment by FObermaier** [comment] 2016-06-09 10:46
The issue is, that the `WmtsParser` flips the `TopLeftCorner` vertices because the EPSG:3006 spatial reference system is defined to be North, East.
For (mainly) used WebMercator this is no issue as the extent in Width and Height are the same.

The snipplet looks like this
```
// Create a new WMTS tile schema 
var tileSchema = new WmtsTileSchema();

// Add the resolutions
foreach (var tileMatrix in tileMatrixSet.TileMatrix)
{
    tileSchema.Resolutions.Add(ToResolution(tileMatrix, ordinateOrder, unitOfMeasure.ToMeter, ss));
}

tileSchema.Extent = ToExtent(tileMatrixSet, tileSchema, new [] {0, 1} /*ordinateOrder*/);
```


I'm not sure where `ordinateOrder` reindexing is supposed to occur and where not.

**Comment by pedwik** [comment] 2016-06-09 11:53
Works great with the fix!

**Comment by pauldendulk** [comment] 2016-06-09 12:09
Great find Felix. I had actually spend quite some time on it yesterday evening with no result. 

WMTS works correctly for the dutch coordinate system EPSG:28992. Can't we use of CrsUnitOfMeasureRegistry to solve this?

**Comment by pedwik** [comment] 2016-06-10 21:19
Thank you for fixing this! For the first time we can now display the map in a DotSpatial application (via an adapted version of the BrutileLayer plugin).

**Comment by pauldendulk** [comment] 2016-06-12 05:51
@FObermaier The ordinate is order is something that should come from the EPSG database right? You had looked into that didn't you? Could this not be solved with something like CrsUnitOfMeasureRegistry?

**Comment by FObermaier** [comment] 2016-06-13 02:05
This is really strange:
This is an excerpt of the capabilities document returned by the service:
```
<TileMatrixSet>
    <ows:Identifier>3006</ows:Identifier>
    <ows:SupportedCRS>urn:ogc:def:crs:EPSG:6.3:3006</ows:SupportedCRS>
    <ows:BoundingBox crs="urn:ogc:def:crs:EPSG:6.3:3006">
        <LowerCorner>-1200000.000000 4305696.000000</LowerCorner>
        <UpperCorner>2994304.000000 8500000.000000</UpperCorner>
    </ows:BoundingBox>
    <TileMatrix>
        <ows:Identifier>0</ows:Identifier>
        <ScaleDenominator>14628571.42857142910361289978</ScaleDenominator>
        <TopLeftCorner>8500000.000000 -1200000.000000</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>4</MatrixWidth>
        <MatrixHeight>4</MatrixHeight>
    </TileMatrix>
    <!-- More -->
</TileMatrixSet>
```
You can see, that x- and y-axes ar not the same ordinate order in the ws:BoundingBox definition and the TopLeftCorner definition.

It states that the coordinate system is EPSG:3006:
```
PROJCS["SWEREF99 TM",
    GEOGCS["SWEREF99",
        DATUM["SWEREF99",
            SPHEROID["GRS 1980",6378137,298.257222101,
                AUTHORITY["EPSG","7019"]],
            TOWGS84[0,0,0,0,0,0,0],
            AUTHORITY["EPSG","6619"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.01745329251994328,
            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","4619"]],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["latitude_of_origin",0],
    PARAMETER["central_meridian",15],
    PARAMETER["scale_factor",0.9996],
    PARAMETER["false_easting",500000],
    PARAMETER["false_northing",0],
    AUTHORITY["EPSG","3006"],
    AXIS["y",EAST],
    AXIS["x",NORTH]]
```
According to this definition, the first y-axis points east and the x-axis points north.
Right now I can't tell if the GetCapabilities document is correct or our implementation.

**Comment by FObermaier** [comment] 2016-06-13 06:39
According to the OGC Web Services Common Standard (OGC 06-121r9), clause 10.2, Table 33,
for `lowerCorner` and `upperCorner` shall contain an 
> Ordered sequence of double values.
The number of axes included, and the order of these axes, shall be as specified by the referenced CRS.

I think the GetCapabilities document is not correct and our implementation is (at least for this concern) valid.
We could allow overriding the _correct_ behavior.

**Comment by pedwik** [comment] 2016-06-13 08:14
I have sent a question on this to Lantmateriet, the Swedish provider. It is to me surprising that it works in QGIS, as if errors in the document are expected.

**Comment by FObermaier** [comment] 2016-06-13 13:28
Just checked with [EPSG](http://www.epsg-registry.org/export.htm?wkt=urn:ogc:def:crs:EPSG::3006) dataset and it seems to confirm that axis orientations are north, east

**Comment by pedwik** [comment] 2016-06-17 08:15
I am hoping that Lantmateriet will correct the problem asap. Does anyone have an idea how this is handled in QGIS?

**Comment by FObermaier** [comment] 2016-06-17 08:35
> I am hoping that Lantmateriet will correct the problem asap

Did they confirm it being a bug?

**Comment by pedwik** [comment] 2016-06-17 09:33
No, I have got no response from then yet. But meanwhile I came across [this blog post](http://gis.stackexchange.com/questions/120325/what-is-proper-succession-of-coordinates-while-specifying-topleftcorner-in-tilem), with exactly the same observation, but the author concludes that "...despite this fact, coordinates in BoundingBox and WGS84BoundingBox are always listed in "natural" succession.".

**Comment by pedwik** [comment] 2016-06-21 09:04
I have no got their response. They confirm that you are right, but say that for "practical and programmatical" reasons they have chosen (x,y) order, and deliberately chosen to violate the OGC standard!

**Comment by FObermaier** [comment] 2016-06-21 12:00
I think https://github.com/BruTile/BruTile/commit/f8a5f7be570d42a99edc455ea430fcca342c1ea6 should address that.

**Comment by FObermaier** [comment] 2016-08-10 10:04
@pedwik: does f8a5f7be570d42a99edc455ea430fcca342c1ea6 address your issue and can we close this issue?

**Closed** 2016-12-07 11:21 UTC
